# Generated by Django 3.0.7 on 2021-04-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_auto_20210410_0425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdpotRequest',
            new_name='AdoptRequest',
        ),
    ]
